### PR TITLE
Admin Dashboard UI

### PR DESCRIPTION
**Pull request by ravimashru**
UI for https://github.com/instituteofai/colexga/issues/1

# Tests
- [x] Show list of tests
- [x] Create test
- [x] Set test as active
- [x] Delete test

---

# Tasks
- [x] Show list of tasks
- [x] Create new task
- [x] Navigate to "edit task" page when new task successfully created
- [x] Edit task
- [x] Delete task

---

- [ ] Make everything look a little prettier

### CODE REVIEW

**Comment by ravimashru** [comment]
The interface looks terrible, haven't put too much into CSS. But the functionality works.

**Review by kumarchandan — CHANGES_REQUESTED** [review]
Testing
---
Tests
 - [x] Show list of tests - works
 - [x] Create test - works
 - [x] Set test as active - works
 - [x] Delete test - works

Tasks
 - [x] Show list of tasks
 - [ ] Create new task
    Failing to read the test_id I suppose
image
 - [x] Navigate to "edit task" page when new task successfully created
 - [x] Edit task
 - [x] Delete task

Comments
---
Creating a task fails.
A dropdown for task type (ESSAY, LETTER, etc) while creating a task
The rest of it looks good to me.

**Comment by ravimashru** [comment]
@kumarchandan 
This is weird. Creating tasks works fine for me. Can you give more detailed steps to reproduce the error?
Here's what I did:
1. Click on "Admin Dashboard"
2. Enter a new test name
3. Click on "Add Test"
4. Click on the name of the newly created test
5. Click on "Add new task"
6. Enter "ESSAY" as type and "This is a question" as question
7. Click on "Save"

The task was saved to the database successfully when I followed these steps.

---

Let us create a dropdown for the task type later when we have all the possible task types stored in the database. I don't think it's a good idea to hard-code the dropdown values in the UI. What do you think?

**Comment by kumarchandan** [comment]
@ravimashru 
Interesting, I tried now and it worked. Perfect! I will merge the PR.

About task type, sure let's do it once we have a master data in place.

**Review by kumarchandan — APPROVED** [review]
LGTM

**Pull request merged**
